/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-02-27 16:21:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class mtop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");

if(request.getAttribute("login")==null){
response.sendRedirect("../index.jsp");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"78\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"../image/bg-1.jpg\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><table width=\"769\" height=\"78\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"../image/bg-2.jpg\" >\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"39\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"../image/bg-3.jpg\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"top\"><table width=\"796\" height=\"32\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"../image/bg-4.jpg\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th><a href=\"index.jsp\"  class=\"a1\">首页</a> |&nbsp;<a href=\"active_select.jsp\" class=\"a1\">物流动态管理</a>&nbsp;| <a href=\"knowledge_select.jsp\" class=\"a1\">物流知识管理</a>&nbsp;|&nbsp;<a href=\"goods_select.jsp\" class=\"a1\">货物管理</a>&nbsp;|&nbsp;<a href=\"car_select.jsp\" class=\"a1\">车辆管理</a>&nbsp;|&nbsp;<a href=\"enterprise_select.jsp\" class=\"a1\">企业管理</a>&nbsp;|&nbsp;&nbsp;<a href=\"placard_select.jsp\" class=\"a1\">公告管理</a>&nbsp;|&nbsp;<a href=\"member_select.jsp\" class=\"a1\">会员管理</a>&nbsp;|&nbsp;<a href=\"tool_assistant.jsp\" class=\"a1\">辅助工具</a>&nbsp;|&nbsp;<a href=\"../logout.jsp\" class=\"a1\">退出</a></th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
