/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-02-27 16:21:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class goods_005fselect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


ResultSet rs=null;
String sql,sqlshow;
String username,login;
int pagesize=10;
int rowcount=0;
int pagecount=1,n;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      com.wy.JDBConnection connection = null;
      connection = (com.wy.JDBConnection) _jspx_page_context.getAttribute("connection", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (connection == null){
        connection = new com.wy.JDBConnection();
        _jspx_page_context.setAttribute("connection", connection, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/style.css\">\r\n");
      out.write("<title>\r\n");
      out.write("Goods_show page\r\n");
      out.write("</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\">\r\n");

login=(String)session.getAttribute("login");
 username=(String)session.getAttribute("name");
if(login==null)
{

      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("alert(\"您还未登录，不能浏览详细信息！！！\");\r\n");
      out.write("</script>\r\n");

response.sendRedirect("login.jsp");
}

      out.write(' ');
      out.write(' ');
      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("<table width=\"786\"  border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FFFFFF\" bordercolordark=\"#333333\" bordercolorlight=\"#FFFFFF\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <td width=\"786\" colspan=\"9\">\r\n");
      out.write("  \r\n");
      out.write("      <p align=\"center\">货物信息\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"786\" height=\"30\" colspan=\"9\" align=\"right\"><a href=\"goods_add.jsp\">发布信息...</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr align=\"center\">\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">货物类型</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">货物名称</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">货物数量</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">数量单位</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">起始省份</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">起始城市</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">抵达省份</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\" align=\"center\">抵达城市</td>\r\n");
      out.write("    <td width=\"786\" height=\"29\">操作</td>\r\n");
      out.write("  </tr>\r\n");

    sql="select * from tb_GoodsMeg order by IssueDate desc";
try
{
 rs=connection.executeQuery(sql);
if(!rs.next())
{

      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\talert(\"没有货物信息\");\r\n");
      out.write("</script>\r\n");

}else
{
rs.last();
rowcount=rs.getRow();
int showpage=1;
pagecount=((rowcount%pagesize)==0?(rowcount/pagesize):(rowcount/pagesize)+1);
 String topage=request.getParameter("topage");
if(topage!=null)
{
showpage=Integer.parseInt(topage);
if(showpage>pagecount){
  showpage=pagecount;
  }else if(showpage<=0){
  showpage=1;
  }
}
rs.absolute((showpage-1)*pagesize+1);
for(int i=1;i<=pagesize;i++)
{
n=rs.getInt("ID");

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("GoodsStyle"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("GoodsName"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("GoodsNumber"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("GoodsUnit"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("StartProvince"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("StartCity"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("EndProvince"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\" align=\"center\">");
      out.print(rs.getString("EndCity"));
      out.write("</td>\r\n");
      out.write("<td width=\"786\" height=\"29\"> <p align=\"center\">\r\n");
      out.write("  <a href=\"goods_xiangxi.jsp?id=");
      out.print(n);
      out.write("\">详细</a></td>\r\n");
      out.write("</tr>\r\n");

if(!rs.next())
break;
}

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td width=\"786\" height=\"30\" colspan=\"9\" align=\"right\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"786\" align=\"center\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("    <td width=\"786\" height=\"30\" colspan=\"9\" align=\"right\">\r\n");
      out.write("        共");
      out.print(pagecount);
      out.write("页&nbsp;&nbsp;\r\n");
      out.write("        <a href=\"goods_select.jsp?topage=");
      out.print(1);
      out.write("\">第一页</a>&nbsp;&nbsp;\r\n");
      out.write("        <a href=\"goods_select.jsp?topage=");
      out.print(showpage-1);
      out.write("\">上一页</a>&nbsp;&nbsp;\r\n");
      out.write("        <a href=\"goods_select.jsp?topage=");
      out.print(showpage+1);
      out.write("\">下一页</a>&nbsp;&nbsp;\r\n");
      out.write("        <a href=\"goods_select.jsp?topage=");
      out.print(pagecount);
      out.write("\">最后一页</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");

}
}catch(Exception e)
{e.printStackTrace();}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
