/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-02-27 16:21:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


ResultSet rs1=null ,goodrs=null;
String sql,goodsql,placardsql,esql,login,username;
int code,gcode;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      com.wy.JDBConnection connection = null;
      connection = (com.wy.JDBConnection) _jspx_page_context.getAttribute("connection", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (connection == null){
        connection = new com.wy.JDBConnection();
        _jspx_page_context.setAttribute("connection", connection, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/style.css\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<Script language=\"javascript\">\r\n");
      out.write("function check1()\r\n");
      out.write("{\r\n");
      out.write("if(form_u.name.value==\"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"请添入姓名\");\r\n");
      out.write("form_u.name.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("if(form_u.password.value==\"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"请添入密码\");\r\n");
      out.write("form_u.password.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</Script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body  link=\"#669900\" alink=\"#FFCC66\" vlink=\"#FF3300\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("<table width=\"786\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"202\" height=\"255\" valign=\"top\" background=\"image/8.jpg\">\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left.jsp", out, true);
      out.write("</td>\r\n");
      out.write("    <td width=\"484\" valign=\"top\"><table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><img src=\"image/13.jpg\" width=\"370\" height=\"39\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("      <table width=\"370\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/14.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td valign=\"top\">\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <table width=\"370\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");

goodsql="select ID,GoodsStyle,GoodsName,StartProvince,StartCity,EndProvince,EndCity,Style,UserName from tb_GoodsMeg order by IssueDate desc limit 0,8";
try{
rs1=connection.executeQuery(goodsql);
while(rs1.next()){
gcode=rs1.getInt("ID");

      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"36\" height=\"25\">&nbsp;</td>\r\n");
      out.write("              <td width=\"334\"><a href=\"goods_xiangxi.jsp?id=");
      out.print(gcode);
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(rs1.getString("GoodsStyle"));
      out.write('-');
      out.write('-');
      out.print(rs1.getString("GoodsName"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("StartProvince"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("StartCity"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("EndProvince"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("EndCity"));
      out.write(" \r\n");
      out.write("\t\t\t\t\t</a></td>\r\n");
      out.write("            </tr>\r\n");

}
}catch(Exception e)
{e.printStackTrace();}

      out.write("\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("              <td width=\"36\" height=\"25\">&nbsp;</td>\r\n");
      out.write("              <td width=\"334\" align=\"right\"><a href=\"goods_select.jsp\">&nbsp;>>>更多信息&nbsp;&nbsp;&nbsp;</a></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\t\t  \t\t  </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><img src=\"image/16.jpg\" width=\"370\" height=\"23\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"370\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/17.jpg\">\r\n");
      out.write("                ");

sql="select Code,TradeMark,Brand,Style,CarLoad,TranspotStyle,UserName from tb_CarMessage order by IssueDate desc limit 0,8";
 try
{
 rs1=connection.executeQuery(sql);
while(rs1.next())
{
code=rs1.getInt("Code");

      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"36\" height=\"25\">&nbsp;</td>\r\n");
      out.write("          <td width=\"334\"><a href=\"car_show.jsp?id=");
      out.print(code);
      out.write('"');
      out.write('>');
      out.print(rs1.getString("TradeMark"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("Brand"));
      out.write(" - -");
      out.print(rs1.getString("Style"));
      out.write('-');
      out.write('-');
      out.print(rs1.getString("CarLoad"));
      out.write("吨- -");
      out.print(rs1.getString("TranspotStyle"));
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

}
}catch(Exception e)
{e.printStackTrace();}

      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"36\" height=\"25\">&nbsp;</td>\r\n");
      out.write("          <td width=\"334\" align=\"right\"><a href=\"car_select.jsp\">&nbsp;>>>更多信息&nbsp;&nbsp;&nbsp;</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><img src=\"image/18.jpg\" width=\"370\" height=\"29\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"370\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/19.jpg\">\r\n");
      out.write("                  ");

sql="select ID,EnterpriseSort,EnterpriseName,Operation,WorkArea,Address,UserName from tb_Enterprise order by IssueDate desc limit 0,7";
 try
{
 rs1=connection.executeQuery(sql);
while(rs1.next())
{
code=rs1.getInt("ID");

      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"36\" height=\"25\">&nbsp;</td>\r\n");
      out.write("          <td width=\"334\"><a href=\"enterprise_show.jsp?id=");
      out.print(code);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(rs1.getString("EnterpriseSort"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("EnterpriseName"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("Operation"));
      out.write('-');
      out.write(' ');
      out.write('-');
      out.print(rs1.getString("WorkArea"));
      out.write("\r\n");
      out.write("\t\t\t\t\t  </a>     </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

}
}catch(Exception e)
{e.printStackTrace();}

      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"36\" height=\"25\">&nbsp;</td>\r\n");
      out.write("          <td width=\"334\" align=\"right\"><a href=\"enterprise_select.jsp\">&nbsp;>>>更多信息&nbsp;&nbsp;&nbsp;</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table></td><!--存放中间的代码-->\r\n");
      out.write("    <td valign=\"top\" width=\"215\" background=\"image/12.jpg\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "right.jsp", out, true);
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "down.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
