/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-02-27 16:21:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      com.wy.JDBConnection connection = null;
      connection = (com.wy.JDBConnection) _jspx_page_context.getAttribute("connection", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (connection == null){
        connection = new com.wy.JDBConnection();
        _jspx_page_context.setAttribute("connection", connection, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String login=(String)session.getAttribute("login");
String username=(String)session.getAttribute("name");

      out.write("\r\n");
      out.write("<table width=\"202\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"202\"><img src=\"image/7.jpg\" width=\"202\" height=\"39\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t\r\n");
      out.write("\t  <table width=\"202\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/8.jpg\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
if(login==null || login==""){
      out.write("<form method=\"POST\" action=\"login_config.jsp\" name=\"form_u\">\r\n");
      out.write("<table width=\"91%\"  height=\"87\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"32%\" height=\"30\" align=\"center\" valign=\"bottom\"><div align=\"right\">用户名</div></td>\r\n");
      out.write("            <td width=\"68%\" align=\"center\" valign=\"bottom\"><input name=\"name\" type=\"text\" size=\"16\" maxlength=\"20\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"30\" align=\"center\"><div align=\"right\">密码</div></td>\r\n");
      out.write("            <td height=\"20\" align=\"center\"><input type=\"password\" name=\"password\" size=\"16\" maxlength=\"20\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"40\" colspan=\"2\" align=\"center\" valign=\"middle\">\r\n");
      out.write("              <input type=\"submit\" value=\"提交\" name=\"login\" onClick=\"return check1()\"> \r\n");
      out.write("\t\t\t   &nbsp;<input type=\"reset\" value=\"重置\"><br><br>\r\n");
      out.write("                   <a href=\"register.jsp\">新注册</a>\r\n");
      out.write("            &nbsp;<a href=\"found.jsp\">找回密码</a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table> \r\n");
      out.write("</form>\r\n");
      out.write(" ");
}else if(login.equals("success")){
      out.write("\r\n");
      out.write("<table width=\"92%\" height=\"18\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("            <td  height=\"18\" align=\"center\">欢迎");
      out.print(username);
      out.write("回来</td>          \r\n");
      out.write("        </tr> \r\n");
      out.write(" </table>\r\n");
}
      out.write("\t\r\n");
      out.write("<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><img src=\"image/9.jpg\" width=\"201\" height=\"5\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t <img src=\"image/111.jpg\" >");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
