/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-02-27 16:21:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>\r\n");
      out.write("register\r\n");
      out.write("</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<link href=\"CSS/style.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("      function check(){\r\n");
      out.write("\t\tif(form1.name.value==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入你的用户名\");\r\n");
      out.write("\t\t\tform1.name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\tif(form1.password.value==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入你注册的密码\");\r\n");
      out.write("\t\t\tform1.password.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form1.repassword.value==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入确认密码\");\r\n");
      out.write("\t\t\tform1.repassword.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form1.password.value!=form1.repassword.value){\r\n");
      out.write("\t\t\talert(\"你输入的两次密码不一致\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form1.email.value==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入你的Email址\");\r\n");
      out.write("\t\t\tform1.email.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tif(form1.phone.value==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入你的联系电话\");\r\n");
      out.write("\t\t\tform1.phone.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form1.question.value==\"\"){\r\n");
      out.write("\t\t\talert(\"输入密码提示问题便于取回密码\");\r\n");
      out.write("\t\t\tform1.question.focus;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form1.result.value==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入回答问题的答案\");\r\n");
      out.write("\t\t\tform1.result.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body ><center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form method=\"POST\" action=\"regist_config.jsp\" name=\"form1\">\r\n");
      out.write(" \r\n");
      out.write(" <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td  height=\"80\" align=\"center\" background=\"image/1.jpg\">\r\n");
      out.write("\t\r\n");
      out.write("      <table height=\"80\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/2.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"787\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0\" width=\"100%\" height=\"75\">\r\n");
      out.write("    <param name=\"movie\" value=\"top.swf\" />\r\n");
      out.write("    <param name=\"quality\" value=\"high\" />\r\n");
      out.write("    <param name=\"wmode\" value=\"transparent\" />\r\n");
      out.write("    <embed src=\"image/top.swf\" width=\"100%\" height=\"75\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" wmode=\"transparent\"></embed>\r\n");
      out.write("  </object></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("\t  \r\n");
      out.write(" \t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"42\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/20.jpg\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"bottom\"><table width=\"100\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><img src=\"image/21.jpg\" width=\"791\" height=\"35\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table width=\"791\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/22.jpg\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"63\"><div align=\"center\">\r\n");
      out.write("      <p><b>会员注册</b></p>\r\n");
      out.write("      </div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write(" \r\n");
      out.write("<table width=\"791\" height=\"205\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/23.jpg\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"46%\" align=\"left\" height=\"27\"><div align=\"right\">用户名：</div></td>\r\n");
      out.write("    <td width=\"54%\" align=\"left\"><input type=\"text\" name=\"name\" size=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"46%\" height=\"27\">\r\n");
      out.write("      <p align=\"right\">密码：</p>    </td>\r\n");
      out.write("    <td width=\"54%\"><input type=\"password\" name=\"password\" size=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"46%\" height=\"27\">\r\n");
      out.write("      <p align=\"right\">确认密码：</p>    </td>\r\n");
      out.write("    <td width=\"54%\"><input name=\"repassword\" type=\"password\" size=\"20\" maxlength=\"16\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("<td width=\"46%\" height=\"27\">\r\n");
      out.write("      <div align=\"right\">性别： </div></td>\r\n");
      out.write("  <td width=\"54%\">&nbsp; 男\r\n");
      out.write("    <input type=\"radio\" value=\"man\" checked name=\"sex\">\r\n");
      out.write("    &nbsp; 女\r\n");
      out.write("    <input type=\"radio\" name=\"sex\" value=\"moman\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"46%\" height=\"27\">\r\n");
      out.write("      <p align=\"right\">电话：</p>    </td>\r\n");
      out.write("    <td width=\"54%\"><input type=\"text\" name=\"phone\" size=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"46%\" height=\"27\">\r\n");
      out.write("      <p align=\"right\">Email：</p>    </td>\r\n");
      out.write("    <td width=\"54%\"><input type=\"text\" name=\"email\" size=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"46%\" height=\"27\">\r\n");
      out.write("    <p align=\"right\">找回密码问题：</p>    </td>\r\n");
      out.write("    <td width=\"54%\"><input type=\"text\" name=\"question\" size=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"46%\" height=\"27\"><div align=\"right\">问题答案：   </div></td>\r\n");
      out.write("    <td width=\"54%\"><input type=\"text\" name=\"result\" size=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"16\" colspan=\"2\">\r\n");
      out.write("      <div align=\"center\">\r\n");
      out.write("          <input type=\"submit\" value=\"注册\"  name=\"Submit\"onClick=\"return check()\"> 　\r\n");
      out.write("          <input type=\"reset\" value=\"重置\">\r\n");
      out.write("        &nbsp;&nbsp;<a href=\"/logistics/index.jsp\">返回</a>\r\n");
      out.write("      </div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><img src=\"image/24.jpg\" width=\"791\" height=\"203\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table></form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
